Eit updates
videolan/dvblast pull request #2
Opened 2018-03-18 19:04 UTC by gfto

2018-03-21 16:37 UTC, cmassiot commented on demux.c
>      if ( b_print_enabled )
Please add a new option to enable/disable printing the EPG to stdout. I am afraid such a high-volume data may flood stdout.

2018-03-21 16:55 UTC, cmassiot requested changes
Except b_print_enabled, LGTM

2018-04-29 14:25 UTC, cmassiot commented
Ping

2018-05-01 06:18 UTC, gfto commented
I'll resubmit the pull with the required fixes.

2018-05-01 06:18 UTC, closed without merging